import LocalizedStrings from 'react-localization'

export const i18n = new LocalizedStrings({
    ru: {
        modalTitle:                 "Система исправления опечаток Etersoft",
        modalInfo:                  "Отредактируйте Ваш вариант текста",
        modalCorrectLabel:          "Ваш вариант",
        modalCorrectHelp:           "Модераторы проверят исправления и внесут поправки в текст",
        modalTypoLabel:             "Выделенный текст",
        modalCommentPlaceholder:    `Например, "опечатка"`,
        modalCommentLabel:          "Пояснения к исправлению (необязательно)",
        errorSelectionLength:       "Длина выделенного текста должна быть от {0} до {1} символов",
        errorCorrectLength:         "Исправление должно быть длиной от {0} до {1} символов",
        errorDoesNotDistinct:       "Исправленный вариант идентичен исходному",
        errorTooOften:              "Вы отправляете исправления слишком часто",
        close:                      "Закрыть",
        saveChanges:                "Отправить",
        messageSuccess:             "Благодарим за отправку опечатки. Мы уже работаем над её исправлением!",
        errorFormContainsErrors:    "Форма отправки содержит ошибки!",
        errorSendFailture:          "Не удалось отправить исправление. Мы уже работаем над решением проблемы!",
        typoHighlightingEnable:     "Проверка правописания на странице",
        typoHighlightingEnabled:    "Подсветка опечаток на странице включена",
        typoHighlightingDisabled:   "Подсветка опечаток на странице выключена",
    },
    en: {
        modalTitle:                 "Typo correction system Etersoft",
        modalInfo:                  "Edit your variant of the text",
        modalCorrectLabel:          "Your variant",
        modalCorrectHelp:           "Moderators will check your proposal correction and fix it!",
        modalTypoLabel:             "Selected text",
        modalCommentPlaceholder:    `"A typo", for example`,
        modalCommentLabel:          "Comment (optional)",
        errorSelectionLength:       "The text length must be in range ({0}-{1})",  
        errorCorrectLength:         "The selected text length must be in range ({0}-{1})",
        errorDoesNotDistinct:       "The original and corrected text are the same",
        errorTooOften:              "You are sending correction requests too often",
        close:                      "Close",
        saveChanges:                "Send",
        messageSuccess:             "Thank you for a typo submitting! We are already working on this report!",
        errorFormContainsErrors:    "The form contains errors!",
        errorSendFailture:          "Failed to send request. We are fixing a problem!",
        typoHighlightingEnable:     "Typo highlighting on this page",
        typoHighlightingEnabled:    "Typo highlighting enabled on this page",
        typoHighlightingDisabled:   "Typo highlighting disabled on this page",
    }
})